---
abstract: 'The great new Config::TOML!'
author:
  - 'Alex Kalderimis <alex.kalderimis@gmail.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-TOML
provides:
  Config::TOML:
    file: lib/Config/TOML.pm
    version: 0.01
requires:
  DateTime: 0
  IO::All: 0
  List::Util: 0
resources:
  license: http://opensource.org/licenses/lgpl-license.php
version: 0.01
